import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Building2, CalendarDays, Check, ChevronRight, Clock3, MapPin, Minus, Plus, Radio, Search, ShieldCheck, Snowflake, Thermometer, X, Zap } from "lucide-react";
import brandAsset from "@/assets/lpres-brand.png.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "National Cold Chain Grid | Book Cold Storage" },
    { name: "description", content: "Search, book and manage trusted cold storage across Nigeria's National Cold Chain Grid." },
    { property: "og:title", content: "National Cold Chain Grid" },
    { property: "og:description", content: "Book and manage trusted cold storage across Nigeria." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: Index,
});

type View = "book" | "monitor" | "manage";
type Facility = { id:string; code:string; name:string; state:string; address:string; types:string[]; cap:number; occ:number; live:boolean; temp:string; humidity:number; price:number };
type Booking = { reference:string; facility:Facility; organisation:string; email:string; grade:string; pallets:number; startDate:string; days:number; total:number };
type LiveReading = { temp:number; humidity:number; voltage:number; available:number; direction:number; updated:Date };

const facilities: Facility[] = [
  { id:"fct", code:"FCT", name:"FCT Cold Storage (Shedda)", state:"FCT", address:"Shedda, Federal Capital Territory", types:["Ultra-Cold","Frozen","Chilled"], cap:480, occ:312, live:true, temp:"3.2°C", humidity:46, price:2500 },
  { id:"adamawa", code:"YOL", name:"Adamawa Cold Storage (Jembutu, Yola)", state:"Adamawa", address:"Jembutu, Yola, Adamawa State", types:["Frozen","Chilled"], cap:240, occ:98, live:true, temp:"2.8°C", humidity:51, price:2500 },
  { id:"edo", code:"BEN", name:"Edo Cold Storage (Benin)", state:"Edo", address:"Benin City, Edo State", types:["Frozen","Chilled"], cap:300, occ:224, live:true, temp:"3.6°C", humidity:48, price:2800 },
  { id:"lagos", code:"LOS", name:"Lagos Cold Storage", state:"Lagos", address:"Lagos State", types:["Ultra-Cold","Frozen","Chilled"], cap:360, occ:189, live:true, temp:"3.1°C", humidity:49, price:3000 },
];
const money=(n:number)=>`₦${n.toLocaleString("en-NG")}`;
function useLiveReadings(){
  const [readings,setReadings]=useState<Record<string,LiveReading>>(()=>Object.fromEntries(facilities.map(f=>[f.id,{temp:Number.parseFloat(f.temp),humidity:f.humidity,voltage:230,available:f.cap-f.occ,direction:1,updated:new Date()}])));
  useEffect(()=>{const timer=window.setInterval(()=>setReadings(current=>Object.fromEntries(facilities.map(f=>{const previous=current[f.id]??{temp:Number.parseFloat(f.temp),humidity:f.humidity,voltage:230,available:f.cap-f.occ,direction:1,updated:new Date()};const direction=Math.random()>.5?1:-1;return [f.id,{temp:Math.min(4.2,Math.max(2.2,previous.temp+direction*.1)),humidity:Math.min(54,Math.max(44,previous.humidity+(Math.random()>.5?1:-1))),voltage:Math.min(234,Math.max(226,previous.voltage+(Math.random()>.5?1:-1))),available:Math.min(f.cap,Math.max(0,previous.available+(Math.random()>.7?(Math.random()>.5?1:-1):0))),direction,updated:new Date()}]}))),1800);return()=>window.clearInterval(timer)},[]);
  return readings;
}

function Index(){
  const [view,setView]=useState<View>("book"); const [location,setLocation]=useState("All locations"); const [grade,setGrade]=useState("Chilled");
  const [date,setDate]=useState("2026-09-15"); const [days,setDays]=useState(7); const [pallets,setPallets]=useState(2); const [searched,setSearched]=useState(false);
  const [booking,setBooking]=useState<Facility|null>(null); const [step,setStep]=useState(1); const [organisation,setOrganisation]=useState(""); const [email,setEmail]=useState(""); const [created,setCreated]=useState<Booking|null>(null);
  const results=useMemo(()=>facilities.filter(f=>(location==="All locations"||f.id===location)&&f.types.includes(grade)),[location,grade]);
  const navigate=(next:View)=>{setView(next);window.scrollTo({top:0,behavior:"smooth"})};
  const confirm=()=>{if(!booking)return; setCreated({reference:`NCCG-${booking.code}-260914`,facility:booking,organisation,email,grade,pallets,startDate:date,days,total:booking.price*pallets*days});setStep(3)};
  return <main className="min-h-screen bg-background text-foreground">
    <header className="grid-header"><button className="brand-button" onClick={()=>navigate("book")} aria-label="National Cold Chain Grid home"><img src={brandAsset.url} alt="L-PRES"/><span><strong>National Cold Chain Grid</strong><small>Powered by L-PRES · Operated by Farm Alert Ltd</small></span></button><nav aria-label="Primary navigation"><button className={view==="book"?"nav-link-active":"nav-link"} onClick={()=>navigate("book")}>Book storage</button><button className={view==="monitor"?"nav-link-active":"nav-link"} onClick={()=>navigate("monitor")}>Live monitoring</button><button className={view==="manage"?"nav-link-active":"nav-link"} onClick={()=>navigate("manage")}>Manage booking</button></nav></header>
    {view==="book"&&<><section className="booking-hero"><div className="hero-copy"><span className="eyebrow"><ShieldCheck size={14}/> Nigeria’s national cold storage network</span><h1>Book cold storage with confidence.</h1><p>Search available facilities, compare live conditions and reserve pallet space in a few simple steps.</p></div><SearchPanel location={location} setLocation={setLocation} grade={grade} setGrade={setGrade} date={date} setDate={setDate} days={days} setDays={setDays} pallets={pallets} setPallets={setPallets} search={()=>{setSearched(true);document.getElementById("results")?.scrollIntoView({behavior:"smooth"})}}/></section><Results facilities={results} grade={grade} days={days} pallets={pallets} searched={searched} onBook={f=>{setBooking(f);setStep(1)}}/><Journey/></>}
    {view==="monitor"&&<Monitoring/>}
    {view==="manage"&&<Manage booking={created} onBook={()=>navigate("book")}/>} 
    <footer><strong>National Cold Chain Grid</strong><span>A Federal Ministry of Livestock Development programme · Powered by L-PRES</span></footer>
    {booking&&<BookingDrawer facility={booking} grade={grade} pallets={pallets} days={days} date={date} step={step} setStep={setStep} organisation={organisation} setOrganisation={setOrganisation} email={email} setEmail={setEmail} close={()=>setBooking(null)} confirm={confirm} manage={()=>{setBooking(null);navigate("manage")}}/>}
  </main>
}

function SearchPanel(p:{location:string;setLocation:(v:string)=>void;grade:string;setGrade:(v:string)=>void;date:string;setDate:(v:string)=>void;days:number;setDays:(v:number)=>void;pallets:number;setPallets:(v:number)=>void;search:()=>void}){return <div className="search-panel"><div className="search-tabs"><span className="active">Book storage</span><span>One facility · Confirmed space</span></div><div className="search-grid"><label><span>Facility or state</span><div><MapPin/><select value={p.location} onChange={e=>p.setLocation(e.target.value)}><option>All locations</option>{facilities.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></div></label><label><span>Storage class</span><div><Snowflake/><select value={p.grade} onChange={e=>p.setGrade(e.target.value)}><option>Chilled</option><option>Frozen</option><option>Ultra-Cold</option></select></div></label><label><span>Start date</span><div><CalendarDays/><input type="date" value={p.date} onChange={e=>p.setDate(e.target.value)}/></div></label><label><span>Duration</span><div><Clock3/><select value={p.days} onChange={e=>p.setDays(Number(e.target.value))}><option value={1}>1 day</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div></label><label><span>Pallet spaces</span><div><Building2/><select value={p.pallets} onChange={e=>p.setPallets(Number(e.target.value))}>{[1,2,3,4,5,10,20].map(n=><option key={n}>{n}</option>)}</select></div></label><button className="search-button" onClick={p.search}><Search/>Search availability</button></div></div>}

function Results({facilities:items,grade,days,pallets,searched,onBook}:{facilities:Facility[];grade:string;days:number;pallets:number;searched:boolean;onBook:(f:Facility)=>void}){const readings=useLiveReadings();return <section id="results" className="results-wrap"><div className="results-heading"><div><span className="eyebrow">{searched?"Search results":"Available today"}</span><h2>National Grid facilities</h2></div><span>{items.length} matching location{items.length===1?"":"s"}</span></div><div className="result-list">{items.map((f,i)=>{const reading=readings[f.id];if(!reading)return null;return <article className="result-card" key={f.id}><div className="telemetry"><span className="live-line"><i/>Live conditions</span><strong className="live-value" key={reading.temp}>{reading.temp.toFixed(1)}°C</strong><small>Core temperature</small><b className="live-value" key={reading.humidity}>{reading.humidity}% humidity</b><em>Updated {reading.updated.toLocaleTimeString("en-NG",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</em></div><div className="result-main"><div className="result-top"><div><span className="location-code">{f.code}</span><h3>{f.name}</h3><p><MapPin/>{f.address}</p></div><div className="fare"><small>From</small><strong>{money(f.price)}</strong><span>per pallet / day</span></div></div><div className="grade-row">{f.types.map(t=><span className={t===grade?"selected-grade":""} key={t}><Snowflake/>{t}</span>)}</div><div className="result-foot"><div className="availability"><div><span style={{width:`${Math.round((f.cap-reading.available)/f.cap*100)}%`}}/></div><strong className="live-value" key={reading.available}>{reading.available} spaces available</strong></div><div className="quote"><span>{pallets} pallet{pallets>1?"s":""} · {days} day{days>1?"s":""}</span><strong>{money(f.price*pallets*days)}</strong></div><button className="book-button" onClick={()=>onBook(f)}>Select space<ChevronRight/></button></div></div>{i===0&&<span className="recommended">Recommended</span>}</article>})}</div></section>}

function Journey(){return <section className="journey"><div><span className="eyebrow">Simple and accountable</span><h2>From search to service in four steps</h2></div><ol>{[["01","Search","Choose a facility, storage class and dates."],["02","Compare","Review availability, live conditions and price."],["03","Book","Add your organisation details and confirm."],["04","Manage","Track conditions and retrieve your records."]].map(([n,t,d])=><li key={n}><span>{n}</span><strong>{t}</strong><p>{d}</p></li>)}</ol></section>}

function Monitoring(){
  const readings=useLiveReadings();
  return <section className="page-wrap"><div className="page-heading monitor-heading"><div><span className="eyebrow"><i className="pulse-dot"/>National Grid live view</span><h1>Facility conditions</h1><p>Live sensor readings across all active cold storage locations.</p></div><span className="stream-status"><Radio/> Receiving live telemetry</span></div><div className="monitor-list">{facilities.map(f=>{const reading=readings[f.id];if(!reading)return null;return <article className="monitor-card" key={f.id}><div className="monitor-facility"><span className="location-code">{f.code}</span><h2>{f.name}</h2><p>{f.address}</p><span className="last-signal"><i/>Signal received {reading.updated.toLocaleTimeString("en-NG",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</span></div><div className="condition-grid"><Condition icon={<Thermometer/>} label="Temperature" value={`${reading.temp.toFixed(1)}°C`} direction={reading.direction}/><Condition icon={<Activity/>} label="Humidity" value={`${reading.humidity}%`} direction={-reading.direction}/><Condition icon={<Zap/>} label="Mains voltage" value={`${reading.voltage}V`} direction={reading.direction}/><Condition icon={<Building2/>} label="Available" value={`${reading.available}`} direction={0}/></div></article>})}</div></section>}
function Condition({icon,label,value,direction}:{icon:React.ReactNode;label:string;value:string;direction:number}){return <div className="condition"><div className="condition-signal"><span>{icon}</span><i/><i/><i/><i/></div><small>{label}</small><strong className="live-value" key={value}>{value}</strong><em><Check/>In range {direction>0?<ArrowUpRight/>:direction<0?<ArrowDownRight/>:null}</em></div>}
function Manage({booking,onBook}:{booking:Booking|null;onBook:()=>void}){return <section className="page-wrap"><div className="page-heading"><span className="eyebrow">Manage booking</span><h1>Your cold-chain service</h1><p>View your reservation, live storage conditions and service records.</p></div>{booking?<article className="manage-card"><div className="manage-title"><span className="status-live">Confirmed</span><small>Booking reference</small><b>{booking.reference}</b><h2>{booking.facility.name}</h2><p>{booking.organisation} · {booking.grade} · {booking.pallets} pallet spaces</p></div><div className="manage-detail"><span><small>Starts</small><strong>{booking.startDate}</strong></span><span><small>Duration</small><strong>{booking.days} days</strong></span><span><small>Total paid</small><strong>{money(booking.total)}</strong></span></div><div className="manage-actions"><button className="btn-secondary">View temperature log</button><button className="btn-primary">Download booking record</button></div></article>:<div className="empty-state"><Snowflake/><h2>No active booking</h2><p>Your confirmed reservations will appear here.</p><button className="btn-primary" onClick={onBook}>Book cold storage<ArrowRight/></button></div>}</section>}

function BookingDrawer(p:{facility:Facility;grade:string;pallets:number;days:number;date:string;step:number;setStep:(n:number)=>void;organisation:string;setOrganisation:(v:string)=>void;email:string;setEmail:(v:string)=>void;close:()=>void;confirm:()=>void;manage:()=>void}){const total=p.facility.price*p.pallets*p.days;return <div className="drawer-layer"><button className="drawer-backdrop" onClick={p.close} aria-label="Close booking"/><aside className="drawer"><div className="drawer-top"><div><small>Complete your booking</small><h2>{p.facility.name}</h2></div><button className="icon-button" onClick={p.close} aria-label="Close"><X/></button></div><div className="booking-steps">{["Storage","Contact","Confirmed"].map((s,i)=><span className={p.step>=i+1?"active":""} key={s}><b>{p.step>i+1?<Check/>:i+1}</b>{s}</span>)}</div>{p.step===1&&<div className="drawer-body"><h3>Review your storage selection</h3><div className="ticket-summary"><div><span className="location-code">{p.facility.code}</span><strong>{p.facility.name}</strong><small>{p.facility.address}</small></div><Snowflake/><div><strong>{p.grade}</strong><small>{p.date} · {p.days} days</small></div></div><div className="selection-row"><span>Pallet spaces</span><div><button className="icon-button"><Minus/></button><strong>{p.pallets}</strong><button className="icon-button"><Plus/></button></div></div><Cost total={total}/><button className="btn-primary btn-full" onClick={()=>p.setStep(2)}>Continue to contact<ArrowRight/></button></div>}{p.step===2&&<div className="drawer-body"><h3>Booking contact</h3><label className="form-field"><span>Organisation name</span><input value={p.organisation} onChange={e=>p.setOrganisation(e.target.value)} placeholder="e.g. HealthBridge Nigeria"/></label><label className="form-field"><span>Email address</span><input type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)} placeholder="name@organisation.org"/></label><Cost total={total}/><p className="demo-note">Preview checkout — no real payment will be processed.</p><button disabled={!p.organisation||!p.email} className="btn-primary btn-full" onClick={p.confirm}>Confirm booking · {money(total)}</button></div>}{p.step===3&&<div className="confirmation"><span className="success-mark"><Check/></span><span className="eyebrow">Booking confirmed</span><h2>Your space is reserved.</h2><p>Reference: <strong>NCCG-{p.facility.code}-260914</strong></p><button className="btn-primary btn-full" onClick={p.manage}>Manage my booking<ArrowRight/></button></div>}</aside></div>}
function Cost({total}:{total:number}){return <div className="cost"><span><small>Total service cost</small><b>Storage, monitoring and records included</b></span><strong>{money(total)}</strong></div>}
